apiVersion: v1
kind: Namespace
metadata:
  name: app-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-deploy
  namespace: app-demo
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: app-demo
        image: httpd
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-svc
  namespace: app-demo
  labels:
    app: app-demo
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-demo-ingress
  namespace: app-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "danhdeploy456.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-demo-svc 
            port:
              number: 80
