apiVersion: v1
kind: Namespace
metadata:
  name: app-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-deploy
  namespace: app-demo
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: public-app
  template:
    metadata:
      labels:
        app: public-app
    spec:
      containers:
      - name: public-app
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: web
          containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-svc
  namespace: public-app
  labels:
    app: public-app
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: public-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-demo-ingress
  namespace: app-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "os-sandbox-dns-9f37f08c.hcp.eastus.azmk8s.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-demo-svc 
            port:
              number: 80
